Feature/ra 01
Nidev-lab/react-advanced pull request #5
Opened 2022-07-27 23:08 UTC by alevexler2

2022-07-28 01:50 UTC, Nidev-lab requested changes

2022-07-28 01:50 UTC, Nidev-lab commented on .eslintrc
> +}
Flor, agregale un salto de linea mas al final del archivo porfa.

2022-07-28 01:51 UTC, Nidev-lab commented
El nombre (title) ideal del pr deberia especificar que tipo de soluciones estamos dando al project. Ej. feat(eslint): eslint added to the project.

2022-08-24 16:28 UTC, closed without merging

2022-10-11 08:48 UTC, alevexler2 commented
Perfecto Nico. Gracias por las correcciones ya lo modifico y vuelvo a hacer
el pr

El mié., 27 jul. 2022 22:51, Nico Gonzalez ***@***.***>
escribió:

> El nombre (title) ideal del pr deberia especificar que tipo de soluciones
> estamos dando al project. Ej. feat(eslint): eslint added to the project.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Nidev-lab/react-advanced/pull/5#issuecomment-1197559491>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXGCLV3JF74W2YBMYJ532J3VWHRRPANCNFSM543JCIOA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>